#Reversed integer

Вам дано число целого типа ``a``. Вам необходимо написать функцию, которая принимает это число на вход, а на выход выдает целое число, цифры в котором записаны в обратном порядке.


**Sample Input 1:**

``
a = 123
``

**Sample Output 1:**

``321``

**Sample Input 2:**

``
a = 120
``

**Sample Output 2:**

``21``

**Sample Input 3:**

``
-123
``

**Sample Output 3:**

``321``

In [ ]:
def run1():
    '''
####################
# TASK SOLUTION:   #
# Reversed integer #
####################
'''

    def reverse_number(number: int) -> int:
        '''Return a nosign number where number's digits in reverse order'''
        
        number = str(number)
        #cut sign befor number
        if number[0] == '-' or number[0] == '+':
            number = number[:0:-1]
        else: number = number[::-1]
        return int(number)


    for i in range(int(input('How many times to repeat?: '))):
        print('\n----- SAMPLE',i+1,'-----')
        print(reverse_number.__doc__)
        print(reverse_number.__annotations__)
        print('Revere number:', reverse_number(input('Input number: ')))


print(run1.__doc__)
run1()


####################
# TASK SOLUTION:   #
# Reversed integer #
####################

How many times to repeat?: 6

----- SAMPLE 1 -----
Return a nosign number where number's digits in reverse order
{'number': <class 'int'>, 'return': <class 'int'>}
Input number: 310001
Revere number: 100013

----- SAMPLE 2 -----
Return a nosign number where number's digits in reverse order
{'number': <class 'int'>, 'return': <class 'int'>}
Input number: 310000
Revere number: 13

----- SAMPLE 3 -----
Return a nosign number where number's digits in reverse order
{'number': <class 'int'>, 'return': <class 'int'>}
Input number: +123
Revere number: 321

----- SAMPLE 4 -----
Return a nosign number where number's digits in reverse order
{'number': <class 'int'>, 'return': <class 'int'>}
Input number: -321
Revere number: 123

----- SAMPLE 5 -----
Return a nosign number where number's digits in reverse order
{'number': <class 'int'>, 'return': <class 'int'>}
Input number: 12
Revere number: 21

----- SAMPLE 6 -

#Выколотый квадрат


Напишите функцию, которая принимает единственное число ``n: int``. Это число определяет длину стороны квадрата. Функция должна нарисовать квадрат из звездочек, при этом звездочки должны быть только на ребрах квадрата, центр должен быть выколот.

**Sample Input 1:**

``
n = 5
``

**Sample Output 1:**
```
* * * * *
*       *
*       *
*       *
* * * * *

```

In [ ]:
def run2():
    '''
#####################
# TASK SOLUTION:    #
# Выколотый квадрат #
#####################
'''

    def make_square(side: int) -> None:
        '''Draw n-side squre from stars, n>0'''

        try:
            side = int(side)
            if side <=0: raise ValueError
        except ValueError:
            print('Wrong input! Expected integer number > 0')
            return 'Error'

        border_symbol = '*'
        inner_symbol = ' '

        for i in range(1, side+1):
            if i == 1 or i == side:
                print(border_symbol.rjust(side, border_symbol))
            else:
                print(border_symbol,
                      border_symbol.rjust(side-1, inner_symbol),
                      sep='')


    for i in range(int(input('How many times to repeat?: '))):
        print('\n----- SAMPLE',i+1,'-----')
        print(make_square.__doc__)
        print(make_square.__annotations__)
        make_square(input('Type suare side: '))


print(run2.__doc__)
run2()


#####################
# TASK SOLUTION:    #
# Выколотый квадрат #
#####################

How many times to repeat?: 6

----- SAMPLE 1 -----
Draw n-side squre from stars, n>0
{'side': <class 'int'>, 'return': None}
Type suare side: -10
Wrong input! Expected integer number > 0

----- SAMPLE 2 -----
Draw n-side squre from stars, n>0
{'side': <class 'int'>, 'return': None}
Type suare side: че?
Wrong input! Expected integer number > 0

----- SAMPLE 3 -----
Draw n-side squre from stars, n>0
{'side': <class 'int'>, 'return': None}
Type suare side: 4
****
*  *
*  *
****

----- SAMPLE 4 -----
Draw n-side squre from stars, n>0
{'side': <class 'int'>, 'return': None}
Type suare side: 2
**
**

----- SAMPLE 5 -----
Draw n-side squre from stars, n>0
{'side': <class 'int'>, 'return': None}
Type suare side: 1
*

----- SAMPLE 6 -----
Draw n-side squre from stars, n>0
{'side': <class 'int'>, 'return': None}
Type suare side: 6
******
*    *
*    *
*    *
*    *
******


#Пермутации

Вам дан массив с целыми числами ``nums``. Напишите функцию, которая принимает на вход данный массив и возвращает все возможные пермутации с данными числами. Возвращать массивы можно в любом порядке.

**Sample Input 1:**

``
nums = [1,2,3]
``

**Sample Output 1:**

``[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]``

**Sample Input 2:**

``
nums = [0,1]
``

**Sample Output 2:**

``[[0,1],[1,0]]``

**Sample Input 3:**

``
nums = [1]
``

**Sample Output 3:**

``[[1]]``

### АХТУНГ! (readme)
МНОГО КОДА НИЖЕ! Конечно, всё делается в два клика функцией permutations() из бибилиотеки itertools, однако это не повод не изобретать велосипед, потому что учёба, а не прод! Додумать полноценный алгоритм перестановки самому за пол дня не удалось, хотя постоянно был близок к разным вариантам. В итоге реализовал понравившийся итеративный на основе циклического сдвига и хитрой проверки. Сам алгоритм коротенький, остальной код - всякие интерфейсные красивости и параметризация работы. Некоторая логика дублируется и в функции и в коде, подготавливающем запуск функции, т.к. функция реализована с возможностью передачи ей необходимых параметров где-то в коде например через другу. функцию, не обязательно задействуя ввод от пользователя. Здечь же параметры спрашиваются у пользователя и вокруг этого построен свой маленький интерфейс. Комменты и надписи в этом ДЗ стараюсь на английском писать, но будет не везде.

In [ ]:
def run3():
    '''
##################
# TASK SOLUTION: #
# Пермутации     #
##################
'''

#---Функция пермутации---
    def permutations(
        nums: list(),
        include_repeats: bool = False
        ) -> dict():
        '''Return all possible permutations for number's list'''
        '''
        Parameters:
        (list) nums: list of numbers
        (bool) include_repeats: is exclude repeats?
                                example 1, 3, 3 and 1, 3, 3
        
        Return:
        dict() where keys:
        'permutations_list': list of lists of number's permutations
        'all_count': count of all permutation
                     (in fact n! where n = count of input numbers)
        'nosame_count': if repeat numbers in input don't exist,
                        then in fact 'Nosame_count' = 'All_count'
                        else exclude repeats: [[1, 3, 3]] instead
                        [[1, 3, 3],[1, 3, 3]]
        'is_all': what staff in 'Permutations' key: unclude or exclude repeats
        '''

        try:
            if type(nums) is not list: raise TypeError
        except:
            print('Wrong input data!')
            return 'Error'
        
        # Список индексов элементов:
        indexes = list(range(len(nums)))
        # Индекс для сравнения, изначально равен индексу последнего элемента:
        last_index = indexes[-1]
        index = last_index
        # Пустой список для добавления вариантов перестановки:
        permnums = []

        #print(indexes) # проследить за перестановкой индексов

        # Алгоритм перестановки:
        # - добавляем первый вариант (неперставленный):
        permnums.append(list(nums[elem] for elem in indexes))
        # - начинаем переставлять:
        while index > 0:
            # Циклический сдвиг влево всех элементов от 0 до index
            tmp = indexes[0]
            for i, el in enumerate(indexes[:index]):
                indexes[i] = indexes[i+1]
            indexes[index] = tmp

            if indexes[index] != index:
                #print(indexes) # проследить за перестановкой индексов
                
                # - добавляем подходящий вариант перестановки
                permnums.append(list(nums[elem] for elem in indexes))
                index = last_index
            else:
                index -= 1

        # Список перестановок сформирован выше, теперь формируем выдачу:        
        all_count = len(permnums)
        
        #Так мы узнаем, были ли повторные числа на входе
        if len(nums) > len(set(nums)):
            '''Сильное колдунство! Список со списками мы хотим превратить
            в список со списками, где одинаковые списки сохранятся
            только в единственном экземпляре! Это будет актуально для случаев,
            когда у введённой последовательности были повторяющиеся числа.
            Что мы уже проверили, поэтому делаем это:
            '''
            nosame = list(map(list, set(map(tuple, permnums))))
            nosame_count = len(nosame)

            if include_repeats:
                is_all = True
            else:
                # Исключаем повторяющиеся варианты перестановок
                # (остаётся один экземпляр из нескольких одинаковых)
                is_all = False
                permnums = nosame
        else:
            # Это значения, если повторяющихся цифр в инпуте не было
            is_all = True
            nosame_count = all_count

        # Словарь на выдачу
        permutations_return = {
            'permutations_list': permnums,
            'all_count': all_count,
            'nosame_count': nosame_count,
            'is_all': is_all}

        return permutations_return
#---Конец функции пермутации---


    # Сколько раз запустить решение?
    for i in range(int(input('How many times to repeat?: '))):
        print('\n----- SAMPLE',i+1,'-----')
        print(permutations.__doc__)
        print(permutations.__annotations__)
        
        # Ввод данных, проверка их корректности и превращение в список
        nums = input('Input separated spaces numbers: ')
        try:
            nums = list(map(int, nums.split()))
        except:
            print('Wrong input data!')
            return 'Error'
            
        # Если в списке есть повторяющиеся числа, можно будет
        # исключить перестановки между одинаковыми числами
        if len(nums) > len(set(nums)):
            is_include_repeats = \
            bool(input('Fined repeated numbers!!!\n'
                     + 'Do you want exclude repeated permutations?\n'
                     + 'Type ANYTHING for NO,\nor EMPTY input for YES:\n'))
        else: is_include_repeats = False

        #Запускаем нашу функцию!
        print('Calculate permutations for number\'s list:', nums, sep='\n')
        output = permutations(nums, include_repeats=is_include_repeats)
        #Формируем варианты вывода:
        print('All possible perms:',output['permutations_list'])
        if (output['all_count'] > output['nosame_count']):
            if output['is_all']:
                print('Showed all permutations, INCLUDE SAMES')
                print('All permutations count:', output['all_count'])
                print('Permutations without sames count:',
                      output['nosame_count'])
            else:
                print('Showed permutations EXCLUDE SAMES')
                print('All permutations count:', output['all_count'])
                print('Permutations without sames count:',
                      output['nosame_count'])
        else:
            print('Total permutations counts:', output['all_count'])


# Запускаем решение!
print(run3.__doc__)
run3()


##################
# TASK SOLUTION: #
# Пермутации     #
##################

How many times to repeat?: 4

----- SAMPLE 1 -----
Return all possible permutations for number's list
{'nums': [], 'include_repeats': <class 'bool'>, 'return': {'permutations_list': [], 'all_count': <class 'int'>, 'nosame_count': <class 'int'>, 'is_all': <class 'bool'>}}
Input separated spaces numbers: 10 20 30
Calculate permutations for number's list:
[10, 20, 30]
All possible perms: [[10, 20, 30], [20, 30, 10], [30, 10, 20], [20, 10, 30], [10, 30, 20], [30, 20, 10]]
Total permutations counts: 6

----- SAMPLE 2 -----
Return all possible permutations for number's list
{'nums': [], 'include_repeats': <class 'bool'>, 'return': {'permutations_list': [], 'all_count': <class 'int'>, 'nosame_count': <class 'int'>, 'is_all': <class 'bool'>}}
Input separated spaces numbers: 300 100 300
Fined repeated numbers!!!
Do you want exclude repeated permutations?
Type ANYTHING for NO,
or EMPTY input for YES:

Calculate permuta

### Почти двойной факториал
Дано натуральное $N \leqslant 100$.  Выведите произведение всех чётных натуральных чисел, не превосходящих $N$.

In [ ]:
def almost_double_factorial(n: int) -> int:
    '''Return product for all even numbers'''
    if n > 100: return 'Toooo biiiiggg! Try smaller number, bro!'
    if n%2 == 0 and  n > 1:
        return n*almost_double_factorial(n-2)
    elif n%2 != 0 and n > 1:
        return almost_double_factorial(n-1)
    else: return 1

def run4():
    '''
###########################
# TASK SOLUTION:          #
# Почти двойной факториал #
###########################
'''

    for i in range(int(input('How many times to repeat?: '))):
        print('\n----- SAMPLE',i+1,'-----')
        print(almost_double_factorial.__doc__)
        print(almost_double_factorial.__annotations__)
        print(almost_double_factorial(int(input('Input number: '))))


print(run4.__doc__)
run4()


###########################
# TASK SOLUTION:          #
# Почти двойной факториал #
###########################

How many times to repeat?: 5

----- SAMPLE 1 -----
Return product for all even numbers
{'n': <class 'int'>, 'return': <class 'int'>}
Input number: 6
48

----- SAMPLE 2 -----
Return product for all even numbers
{'n': <class 'int'>, 'return': <class 'int'>}
Input number: 9
384

----- SAMPLE 3 -----
Return product for all even numbers
{'n': <class 'int'>, 'return': <class 'int'>}
Input number: 25
1961990553600

----- SAMPLE 4 -----
Return product for all even numbers
{'n': <class 'int'>, 'return': <class 'int'>}
Input number: 100
34243224702511976248246432895208185975118675053719198827915654463488000000000000

----- SAMPLE 5 -----
Return product for all even numbers
{'n': <class 'int'>, 'return': <class 'int'>}
Input number: 101
Toooo biiiiggg! Try smaller number, bro!


In [ ]:
N = 25
#YOUR CODE
N_double_fact = almost_double_factorial(N)

assert N_double_fact == 1961990553600, "Something is wrong! Please try again"

N = 100
N_double_fact = almost_double_factorial(N)
assert N_double_fact == 34243224702511976248246432895208185975118675053719198827915654463488000000000000, "Something is wrong! Please try again"

#добавил:
N = 101
N_double_fact = almost_double_factorial(N)
assert N_double_fact == 'Toooo biiiiggg! Try smaller number, bro!', "Something is wrong! Please try again"

### Хитрая сортировка

Пусть у нас есть следующий список, в котором элементы -- tuple из строк:

``items = [('one', 'two'), ('three', 'four'), ('five', 'six'), ('string', 'a')]``

Мы хотим отсортировать этот список по последней букве второго элемента каждого ``tuple``, т.е. получить такой список:

``sorted_items = [('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')]``.
Что нужно вставить вместо "###" в следующем выражении, чтобы получить сортировку?

``sorted_items = sorted(items, key=lambda x: ###)``

In [ ]:
items = [('one', 'two'), ('three', 'four'), ('five', 'six'), ('string', 'a')]

sorted_items = sorted(items, key=lambda x: x[1][-1]) # <<<ВОТ ЭТО!
                      
assert sorted_items == [('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')], \
"Something is wrong! Please try again"

### Еще строки

Вашей программе на вход подаются три строки ``s, a, b``, состоящие из строчных латинских букв.
За одну операцию вы можете заменить все вхождения строки ``a`` в строку ``s`` на строку ``b``.

Например, ``s = "abab", a = "ab", b = "ba"``, тогда после выполнения одной операции строка ``s`` перейдет в строку ``"baba"``, после выполнения двух и операций – в строку ``"bbaa"``, и дальнейшие операции не будут изменять строку ``s``.

Необходимо узнать, после какого минимального количества операций в строке ``s`` не останется вхождений строки ``a``. Если операций потребуется более 1000, выведите ``Impossible``.

Выведите одно число – минимальное число операций, после применения которых в строке ``s`` не останется вхождений строки ``a``, или ``Impossible``, если операций потребуется более 1000.

**Sample Input 1:**

``
ababa
a
b
``

**Sample Output 1:**

``1``

**Sample Input 2:**

``ababa
b
a``

**Sample Output 2:**

``1``

**Sample Input 3:**

``ababa
c
c``

**Sample Output 3:**

``0``

**Sample Input 4:**

``ababac
c
c``

**Sample Output 4:**

``Impossible``


In [ ]:
def run6():
    '''
##################
# TASK SOLUTION: #
# Еще строки     #
##################
'''

    def my_func(s: str, a: str, b: str):
        '''Считает рекурсивно все замены на <b> вхождений <a> в <s>'''

        count = 0
        L = len(a)
        #print(s)
        
        while count <= 1000:
            if s.find(a) == -1:
                return count
            else:
                s = s.replace(a,b)
                count += 1
                #print(s)


        return 'Impossible'


    for i in range(int(input('How many times to repeat?: '))):
        print('\n----- SAMPLE',i+1,'-----')
        print(my_func.__doc__)
        print(my_func.__annotations__)

        in_vars = input('Input s, a, b separeted spaces: ')
        s = in_vars.split()[0]
        a = in_vars.split()[1]
        b = in_vars.split()[2]
        res = my_func(s, a, b)

        if res == 'Impossible': print(res)
        else: print('Need', res, 'iterations')


print(run6.__doc__)
run6()


##################
# TASK SOLUTION: #
# Еще строки     #
##################

How many times to repeat?: 5

----- SAMPLE 1 -----
Считает рекурсивно все замены на <b> вхождений <a> в <s>
{'s': <class 'str'>, 'a': <class 'str'>, 'b': <class 'str'>}
Input s, a, b separeted spaces: abcabc abc d
Need 1 iterations

----- SAMPLE 2 -----
Считает рекурсивно все замены на <b> вхождений <a> в <s>
{'s': <class 'str'>, 'a': <class 'str'>, 'b': <class 'str'>}
Input s, a, b separeted spaces: ababa aba ba
Need 2 iterations

----- SAMPLE 3 -----
Считает рекурсивно все замены на <b> вхождений <a> в <s>
{'s': <class 'str'>, 'a': <class 'str'>, 'b': <class 'str'>}
Input s, a, b separeted spaces: aabababab c b
Need 0 iterations

----- SAMPLE 4 -----
Считает рекурсивно все замены на <b> вхождений <a> в <s>
{'s': <class 'str'>, 'a': <class 'str'>, 'b': <class 'str'>}
Input s, a, b separeted spaces: abbaabbaabbaabba ab ba
Need 8 iterations

----- SAMPLE 5 -----
Считает рекурсивно все замены на <b> вхождений <

### Создание массивов
Дан массив $A[0,\ldots,N-1]$. Напишите функцию, принимающую один обязательный аргумент A и один опциональный аргумент ``erase``, по умолчанию равный 1. Возвратите массив $B[0,\ldots, N-1]$, где $B_i = A_0 + \ldots + A_{i}$ --- массив частичных сумм массива $A$, предварительно удалив из массива $B$ все элементы, равные erase. Постарайтесь сделать это за линейное время без использования Numpy.

In [98]:
def cumsum_and_erase(a: list(), erase: int = 1) -> list():
    '''Makes black magic'''

    b = []
    for i, el in enumerate(a):
        s = sum(a[:i+1])
        if s !=  erase: b.append(s)

    return b

print(cumsum_and_erase.__doc__)
print(cumsum_and_erase.__annotations__)

A = [5, 1, 4, 5, 14]
B = cumsum_and_erase(A, erase=10)

print(A)
print(B)

assert B == [5, 6, 15, 29], "Something is wrong! Please try again"

Makes black magic
{'a': [], 'erase': <class 'int'>, 'return': []}
[5, 1, 4, 5, 14]
[5, 6, 15, 29]


### Обработка текста
Дан список текстов, слова в которых разделены пробелами (можно считать, что знаков препинания нет). Часть слов является "мусорными": в них присутствуют цифры и спецсимволы. Отфильтруйте такие слова из каждого текста. Используйте функции ``str.split``, ``str.isalpha``, ``str.join``, а также [генератор filter](http://pythonicway.com/python-functinal-programming).

In [ ]:
sentences = ['1 thousand devils', 'My name is 9Pasha', 'Room #125 costs $100']

def process(sentences):
    print(sentences)
    
    result = []
    tmplist = []
    for i in range(len(sentences)):
        tmplist.append(list(sentences[i].split()))
        tmplist[i] = list(filter(lambda x: x.isalpha(), tmplist[i]))
        result.append(' '.join(tmplist[i]))
        
    print(result)
    
    return result

assert process(sentences) == ['thousand devils', 'My name is', 'Room costs'], \
"Something is wrong! Please try again"

['1 thousand devils', 'My name is 9Pasha', 'Room #125 costs $100']
['thousand devils', 'My name is', 'Room costs']


#Расстояние Хэмминга

Вам даны две строки, ``a`` и ``b`` одинаковой длины. Необходимо посчитать расстояние Хэмминга между ними, которое определяется как количество символов, которые не совпадают между двумя строками в одинаковой позиции.

**Sample Input 1:**

```
a = 'AGCT'
b = 'ACGT'
hamming(a, b)
```

**Sample Output 1:**

``2``

In [1]:
def hamming(a: str, b: str) -> int:
    '''Return hamming'''
    res = 0
    for i in range(len(a)):
        if a[i] != b[i]: res += 1
    return res


def run9():
    '''
#######################
# TASK SOLUTION:      #
# Расстояние Хэмминга #
#######################
'''

    for i in range(int(input('How many times to repeat?: '))):
        print('\n----- SAMPLE',i+1,'-----')
        print(hamming.__doc__)
        print(hamming.__annotations__)
        
        a = input('Input <A> word: ')
        b = input('Input <B> word: ')
        print('Hamming =',hamming(a, b))


print(run9.__doc__)
run9()


assert hamming("AGCT", "ACGT") == 2
assert hamming("AGOCT", "ACOGT") == 2
assert hamming("ACCT", "ACGT") == 1


#######################
# TASK SOLUTION:      #
# Расстояние Хэмминга #
#######################

How many times to repeat?: 3

----- SAMPLE 1 -----
Return hamming
{'a': <class 'str'>, 'b': <class 'str'>, 'return': <class 'int'>}
Input <A> word: abcd
Input <B> word: abcd
Hamming = 0

----- SAMPLE 2 -----
Return hamming
{'a': <class 'str'>, 'b': <class 'str'>, 'return': <class 'int'>}
Input <A> word: accd
Input <B> word: abbd
Hamming = 2

----- SAMPLE 3 -----
Return hamming
{'a': <class 'str'>, 'b': <class 'str'>, 'return': <class 'int'>}
Input <A> word: abcd
Input <B> word: dcba
Hamming = 4


### Numpy

In [3]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [80]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь

print('Размерность а:', np.ndim(a))
print('Размерность b:', np.ndim(b))
print('\n')

def forma(x):
    '''Превратим вывод от shape() в словестный вывод (для любой размерности)'''
    res = ''
    L = np.shape(x)
    for i, el in enumerate(L):
        res += (' на ' + str(el)) if i > 0 else str(el)
    return res


print('Размер (форма) а:', forma(a), 'элементов')
print('Размер (форма) b:', forma(b), 'элементов')
print('\n\n')
# ========
print(a)
print(b)

Размерность а: 2
Размерность b: 2


Размер (форма) а: 100 на 100 элементов
Размер (форма) b: 100 на 100 элементов



[[0.81298507 0.91449151 0.05655686 ... 0.08932963 0.67611225 0.37685506]
 [0.40560372 0.84569848 0.08819376 ... 0.90508079 0.65778109 0.17140102]
 [0.98287582 0.34657395 0.94462321 ... 0.33151339 0.18051414 0.44136657]
 ...
 [0.50250755 0.69943245 0.34564099 ... 0.18385174 0.62015069 0.84041655]
 [0.02799098 0.39457442 0.38687739 ... 0.04906035 0.55254949 0.66237573]
 [0.19898477 0.51978249 0.82747853 ... 0.51140468 0.36691377 0.02495858]]
[[0.80246608 0.83205784 0.89276143 ... 0.49051866 0.19977663 0.59337228]
 [0.239075   0.1693943  0.50350765 ... 0.45949357 0.06016528 0.89705464]
 [0.145985   0.4510614  0.04212455 ... 0.90091357 0.31292409 0.1968776 ]
 ...
 [0.24969354 0.45121353 0.05141016 ... 0.26917674 0.97149855 0.35283609]
 [0.94268769 0.1769603  0.21052244 ... 0.32160127 0.83730633 0.72184556]
 [0.27885439 0.55147056 0.92875751 ... 0.65873646 0.62317663 0.013150

In [91]:
def mult(a, b):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy (может помочь функция zip)
    """
    
    axi = range(np.shape(a)[0]) # список индексов по строкам а-матрицы
    ayi = range(np.shape(a)[1]) # список индексов по столбцам а-матрицы
    byi = range(np.shape(b)[1]) # список индексов по столбцам b-матрицы

    # Матрица нужного размера для сохранения результатов перемножения
    # строк будет столько же сколько у а-матрицы, а столбцов будет столько же,
    # сколько столбцов у b-матрицы
    c = np.zeros((len(axi), len(byi)))

    for n in axi:
        for j in byi:
            s = 0
            for i in ayi:
                s += a[n][i]*b[i][j]
            c[n][j] += s
    return c

print(mult(a,b))

[[23.82850092 25.87737217 23.47954394 ... 22.68823084 23.17724973
  25.69403391]
 [26.31239154 26.80678257 22.06392763 ... 23.15250871 24.07593064
  25.93145125]
 [27.41121611 28.85416263 24.20942953 ... 24.18713464 24.25051613
  24.86693991]
 ...
 [26.22518724 26.32593886 23.47818556 ... 24.2622873  22.97952968
  23.89056494]
 [26.38763136 27.54707075 23.5902719  ... 25.36227133 24.85927072
  22.73585246]
 [24.35634625 25.07394362 25.38252119 ... 25.53998354 22.20796959
  25.27336341]]


In [92]:
def np_mult(a, b):
    """  
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    return np.matmul(a, b)

print(np_mult(a, b))

[[23.82850092 25.87737217 23.47954394 ... 22.68823084 23.17724973
  25.69403391]
 [26.31239154 26.80678257 22.06392763 ... 23.15250871 24.07593064
  25.93145125]
 [27.41121611 28.85416263 24.20942953 ... 24.18713464 24.25051613
  24.86693991]
 ...
 [26.22518724 26.32593886 23.47818556 ... 24.2622873  22.97952968
  23.89056494]
 [26.38763136 27.54707075 23.5902719  ... 25.36227133 24.85927072
  22.73585246]
 [24.35634625 25.07394362 25.38252119 ... 25.53998354 22.20796959
  25.27336341]]


In [93]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 624 ms, sys: 0 ns, total: 624 ms
Wall time: 626 ms


In [94]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 2.86 ms, sys: 0 ns, total: 2.86 ms
Wall time: 1.46 ms


In [95]:
# проверим корректность
assert np.allclose(np.array(M1), M2)